# Generated by Django 4.2.7 on 2025-10-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsMetrics',
            fields=[
                ('metric_id', models.AutoField(primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_metrics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSnapshots',
            fields=[
                ('snapshot_id', models.AutoField(primary_key=True, serialize=False)),
                ('snapshot_type', models.CharField(max_length=50)),
                ('snapshot_date', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_snapshots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=50)),
                ('table_name', models.CharField(max_length=50)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BackupLogs',
            fields=[
                ('backup_id', models.AutoField(primary_key=True, serialize=False)),
                ('backup_date', models.DateTimeField(blank=True, null=True)),
                ('backup_type', models.CharField(blank=True, max_length=50, null=True)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'backup_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportItems',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('metric_name', models.CharField(blank=True, max_length=50, null=True)),
                ('metric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('additional_info', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=100)),
                ('report_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'reports',
                'managed': False,
            },
        ),
    ]
